<?php

$storesData = [
    // Abbigliamento e Moda
    [
        'store_name' => 'FashionStyle',
        'description' => 'Ampia selezione di abbigliamento alla moda.',
        'link' => 'https://www.fashionstyle.com/',
        'category_id' => 1,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'ABC123',
        'discount' => 20,
        'commission' => 5,
    ],
    [
        'store_name' => 'ChicWear',
        'description' => 'Abbigliamento elegante e di tendenza per tutte le età.',
        'link' => 'https://www.chicwear.com/',
        'category_id' => 1,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'XYZ789',
        'discount' => 15,
        'commission' => 4,
    ],
    [
        'store_name' => 'SportsGear',
        'description' => 'Abbigliamento sportivo di alta qualità per atleti.',
        'link' => 'https://www.sportsgear.com/',
        'category_id' => 1,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => '123XYZ',
        'discount' => 10,
        'commission' => 3,
    ],
    [
        'store_name' => 'KidsFashion',
        'description' => 'Moda per bambini, abbigliamento carino e colorato.',
        'link' => 'https://www.kidsfashion.com/',
        'category_id' => 1,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'KID456',
        'discount' => 25,
        'commission' => 6,
    ],
    [
        'store_name' => 'CasualThreads',
        'description' => 'Abbigliamento casual per il tempo libero.',
        'link' => 'https://www.casualthreads.com/',
        'category_id' => 1,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'CT789',
        'discount' => 18,
        'commission' => 4.5,
    ],

    // Casa e Giardino
    [
        'store_name' => 'HomeDecor',
        'description' => 'Prodotti per la decorazione della casa e del giardino.',
        'link' => 'https://www.homedecor.com/',
        'category_id' => 2,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'HOME123',
        'discount' => 15,
        'commission' => 4,
    ],
    [
        'store_name' => 'GardenParadise',
        'description' => 'Strumenti e arredamento per il giardino.',
        'link' => 'https://www.gardenparadise.com/',
        'category_id' => 2,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'GARDEN456',
        'discount' => 12,
        'commission' => 3.5,
    ],
    [
        'store_name' => 'FurnitureFinds',
        'description' => 'Mobili per interni ed esterni di alta qualità.',
        'link' => 'https://www.furniturefinds.com/',
        'category_id' => 2,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'FURNITURE789',
        'discount' => 20,
        'commission' => 5,
    ],
    [
        'store_name' => 'KitchenEssentials',
        'description' => 'Accessori e utensili da cucina di design.',
        'link' => 'https://www.kitchenessentials.com/',
        'category_id' => 2,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'KITCHEN123',
        'discount' => 10,
        'commission' => 3.5,
    ],
    [
        'store_name' => 'OutdoorLiving',
        'description' => 'Arredi per esterni e attrezzature per il tempo libero.',
        'link' => 'https://www.outdoorliving.com/',
        'category_id' => 2,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'OUTDOOR456',
        'discount' => 18,
        'commission' => 4,
    ],
        // Elettronica e Tecnologia
    [
        'store_name' => 'TechGadgets',
        'description' => 'Tecnologia all\'avanguardia per gli amanti della tecnologia.',
        'link' => 'https://www.techgadgets.com/',
        'category_id' => 3,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'TECH123',
        'discount' => 15,
        'commission' => 4.5,
    ],
    [
        'store_name' => 'ElectroWorld',
        'description' => 'Una vasta gamma di elettronica e gadget di alta qualità.',
        'link' => 'https://www.electroworld.com/',
        'category_id' => 3,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'ELECTRO456',
        'discount' => 10,
        'commission' => 3,
    ],
    [
        'store_name' => 'MobileHaven',
        'description' => 'Smartphone, tablet e accessori per la tua vita mobile.',
        'link' => 'https://www.mobilehaven.com/',
        'category_id' => 3,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'MOBILE789',
        'discount' => 20,
        'commission' => 5,
    ],
    [
        'store_name' => 'GamingZone',
        'description' => 'Tutto per i giocatori: console, giochi e accessori.',
        'link' => 'https://www.gamingzone.com/',
        'category_id' => 3,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'GAMING123',
        'discount' => 12,
        'commission' => 3.5,
    ],
    [
        'store_name' => 'TechSupplies',
        'description' => 'Forniture per ufficio e tecnologia per le aziende.',
        'link' => 'https://www.techsupplies.com/',
        'category_id' => 3,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'TECHSUP456',
        'discount' => 18,
        'commission' => 4,
    ],

    // Salute e Bellezza
    [
        'store_name' => 'HealthHaven',
        'description' => 'Prodotti per la salute e il benessere personale.',
        'link' => 'https://www.healthhaven.com/',
        'category_id' => 4,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'HEALTH123',
        'discount' => 20,
        'commission' => 6,
    ],
    [
        'store_name' => 'BeautyWorld',
        'description' => 'Prodotti di bellezza e cosmetici di alta qualità.',
        'link' => 'https://www.beautyworld.com/',
        'category_id' => 4,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'BEAUTY456',
        'discount' => 15,
        'commission' => 4.5,
    ],
    [
        'store_name' => 'FitnessHub',
        'description' => "Attrezzature e integratori per il fitness e l'allenamento.",
        'link' => 'https://www.fitnesshub.com/',
        'category_id' => 4,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'FITNESS789',
        'discount' => 10,
        'commission' => 3.5,
    ],
    [
        'store_name' => 'WellnessStore',
        'description' => 'Prodotti per il benessere e il relax.',
        'link' => 'https://www.wellnessstore.com/',
        'category_id' => 4,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'WELLNESS123',
        'discount' => 25,
        'commission' => 6.5,
    ],
    [
        'store_name' => 'MediMart',
        'description' => 'Farmaci e prodotti medici di qualità.',
        'link' => 'https://www.medimart.com/',
        'category_id' => 4,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'MEDIMART456',
        'discount' => 12,
        'commission' => 4,
    ],
    // Viaggi e Vacanze
    [
        'store_name' => 'TravelWorld',
        'description' => 'Prenota voli, hotel e pacchetti vacanza in tutto il mondo.',
        'link' => 'https://www.travelworld.com/',
        'category_id' => 5,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'TRAVEL123',
        'discount' => 15,
        'commission' => 4.5,
    ],
    [
        'store_name' => 'AdventureSeekers',
        'description' => 'Esperienze di avventura e viaggi eccezionali.',
        'link' => 'https://www.adventureseekers.com/',
        'category_id' => 5,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'ADVENTURE456',
        'discount' => 10,
        'commission' => 3.5,
    ],
    [
        'store_name' => 'CruiseMasters',
        'description' => "Crociere e viaggi in nave per l'esploratore in te.",
        'link' => 'https://www.cruisemasters.com/',
        'category_id' => 5,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'CRUISE789',
        'discount' => 20,
        'commission' => 5,
    ],
    [
        'store_name' => 'BeachParadise',
        'description' => 'Vacanze al mare per rilassarsi sotto il sole.',
        'link' => 'https://www.beachparadise.com/',
        'category_id' => 5,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'BEACH123',
        'discount' => 12,
        'commission' => 3.5,
    ],
    [
        'store_name' => 'ExploreNations',
        'description' => 'Viaggi avventurosi in luoghi esotici in tutto il mondo.',
        'link' => 'https://www.explorenations.com/',
        'category_id' => 5,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'EXPLORE456',
        'discount' => 18,
        'commission' => 4,
    ],

    // Cibo e Bevande
    [
        'store_name' => 'FoodDelights',
        'description' => 'Ordina cibo delizioso e bevande online.',
        'link' => 'https://www.fooddelights.com/',
        'category_id' => 6,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'FOOD123',
        'discount' => 15,
        'commission' => 4.5,
    ],
    [
        'store_name' => 'WineWorld',
        'description' => 'Vini pregiati e bevande alcoliche di alta qualità.',
        'link' => 'https://www.wineworld.com/',
        'category_id' => 6,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'WINE456',
        'discount' => 10,
        'commission' => 3.5,
    ],
    [
        'store_name' => 'CoffeeHeaven',
        'description' => 'Caffè e accessori per gli amanti del caffè.',
        'link' => 'https://www.coffeeheaven.com/',
        'category_id' => 6,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'COFFEE789',
        'discount' => 20,
        'commission' => 5,
    ],
    [
        'store_name' => 'GourmetEats',
        'description' => 'Cibi gourmet e prelibatezze culinarie.',
        'link' => 'https://www.gourmeteats.com/',
        'category_id' => 6,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'GOURMET123',
        'discount' => 12,
        'commission' => 3.5,
    ],
    [
        'store_name' => 'HealthyBites',
        'description' => 'Alimenti salutari e prodotti per la dieta.',
        'link' => 'https://www.healthybites.com/',
        'category_id' => 6,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'HEALTHY456',
        'discount' => 18,
        'commission' => 4,
    ],
    // Sport
    [
        'store_name' => 'SportGearPro',
        'description' => 'Attrezzature sportive di alta qualità per tutti gli sport.',
        'link' => 'https://www.sportgearpro.com/',
        'category_id' => 7,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'SPORT123',
        'discount' => 15,
        'commission' => 4.5,
    ],
    [
        'store_name' => 'AthleteWorld',
        'description' => 'Abbigliamento e attrezzature per gli atleti professionisti.',
        'link' => 'https://www.athleteworld.com/',
        'category_id' => 7,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'ATHLETE456',
        'discount' => 10,
        'commission' => 3.5,
    ],
    [
        'store_name' => 'OutdoorAdventures',
        'description' => "Attrezzature per attività all'aperto e avventure.",
        'link' => 'https://www.outdooradventures.com/',
        'category_id' => 7,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'OUTDOOR123',
        'discount' => 20,
        'commission' => 5,
    ],
    [
        'store_name' => 'TeamSportsHub',
        'description' => 'Abbigliamento e attrezzature per sport di squadra.',
        'link' => 'https://www.teamsportshub.com/',
        'category_id' => 7,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'TEAMSPORT456',
        'discount' => 12,
        'commission' => 3.5,
    ],
    [
        'store_name' => 'BikeWorld',
        'description' => 'Biciclette e accessori per gli amanti del ciclismo.',
        'link' => 'https://www.bikeworld.com/',
        'category_id' => 7,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'BIKE123',
        'discount' => 18,
        'commission' => 4,
    ],

    // Fitness
    [
        'store_name' => 'FitSupplies',
        'description' => "Attrezzature e accessori per il fitness e l'allenamento.",
        'link' => 'https://www.fitsupplies.com/',
        'category_id' => 8,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'FIT123',
        'discount' => 15,
        'commission' => 4.5,
    ],
    [
        'store_name' => 'YogaHeaven',
        'description' => "Prodotti per lo yoga e l'equilibrio mentale e fisico.",
        'link' => 'https://www.yogaheaven.com/',
        'category_id' => 8,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'YOGA456',
        'discount' => 10,
        'commission' => 3.5,
    ],
    [
        'store_name' => 'GymWearPro',
        'description' => "Abbigliamento sportivo per l'allenamento in palestra.",
        'link' => 'https://www.gymwearpro.com/',
        'category_id' => 8,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'GYM123',
        'discount' => 20,
        'commission' => 5,
    ],
    [
        'store_name' => 'FitnessFuel',
        'description' => 'Integratori alimentari e prodotti per il fitness.',
        'link' => 'https://www.fitnessfuel.com/',
        'category_id' => 8,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'FITFUEL456',
        'discount' => 12,
        'commission' => 3.5,
    ],
    [
        'store_name' => 'WorkoutWorld',
        'description' => "Attrezzature per l'allenamento a casa o in palestra.",
        'link' => 'https://www.workoutworld.com/',
        'category_id' => 8,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'WORKOUT123',
        'discount' => 18,
        'commission' => 4,
    ],
    // Servizi
    [
        'store_name' => 'BusinessSolutions',
        'description' => 'Soluzioni aziendali e servizi di consulenza.',
        'link' => 'https://www.businesssolutions.com/',
        'category_id' => 9,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'BUSINESS123',
        'discount' => 10,
        'commission' => 3.5,
    ],
    [
        'store_name' => 'TravelBooking',
        'description' => 'Prenotazione di servizi di viaggio e vacanze.',
        'link' => 'https://www.travelbooking.com/',
        'category_id' => 9,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'TRAVELBOOK456',
        'discount' => 15,
        'commission' => 4.5,
    ],
    [
        'store_name' => 'DesignStudio',
        'description' => 'Servizi di design e sviluppo grafico.',
        'link' => 'https://www.designstudio.com/',
        'category_id' => 9,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'DESIGNSTUDIO789',
        'discount' => 20,
        'commission' => 5,
    ],
    [
        'store_name' => 'TechSupportPro',
        'description' => 'Assistenza tecnica e servizi di supporto informatico.',
        'link' => 'https://www.techsupportpro.com/',
        'category_id' => 9,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'TECHSUPPORT123',
        'discount' => 12,
        'commission' => 3.5,
    ],
    [
        'store_name' => 'EventPlanning',
        'description' => 'Servizi di pianificazione e organizzazione eventi.',
        'link' => 'https://www.eventplanning.com/',
        'category_id' => 9,
        'logo' => '1st-tab.jpg',
        'affiliation_code' => 'EVENT123',
        'discount' => 18,
        'commission' => 4,
    ],
];

return $storesData;
